### ISSUE TITLE
Please tag latest for binary changes

### ISSUE THREAD

**Issue by GearsAD** [felipenoris/Mongoc.jl#12]
Hi,

Great package, thank you for building this. Can you please tag/release with the new binary code it so it can update in Julia's metadata?

P.S. Assuming you're using attobot for Julia metadata updates.

**Comment by dehann** [comment]
Hi, not sure if this is related, but maybe I can help with a suggestion for `fn/refactoring` branch:

```julia
function undef_vector(::T, len::Integer) where T
    @static if VERSION < v"0.7-"
        Vector{T}(len)
    else
        Vector{T}(undef, len)
    end
end
```

**Comment by felipenoris** [comment]
@dehann , you´re right. Thank you!

**Comment by felipenoris** [comment]
https://github.com/JuliaLang/METADATA.jl/pull/18911

**Comment by dehann** [comment]
Thank you very much, sorry for all the traffic.
