### ISSUE TITLE
Catch Mongo Errors

### ISSUE THREAD

**Issue by ivborissov** [felipenoris/Mongoc.jl#15]
Hi, 

Is it possible to catch errors related to MongoDB (DB not available, authentication errors)? For example, now `find` returns `nothing` in both cases: the doc wasn't found or Mongo was not reached (authentication error, not available, etc). For authentication error Julia prints `[ 8072]:    DEBUG:      cluster: Authentication failed: Authentication failed.` but is it possible "catch" such messages to differentiate Mongo errors from "doc not found" or maybe it reasonable to `throw` rather then print such errors?

**Comment by felipenoris** [comment]
Hi! Thanks for reporting this!

Can you provide a code example that demonstrates the issue?

**Comment by ivborissov** [comment]
Thanks for quick response! I don't consider it as an issue but I am looking for a way to catch the follwing connection errors:
```
client = Mongoc.Client("wrong_url")
collection = client["db_name"]["collection_name"]
res = Mongoc.find_one(collection, Mongoc.BSON("""....."""))
```
I get 
```
[ 8072]:    DEBUG:      cluster: Authentication failed: Authentication failed.
res = nothing
```
My use case is the following. I am writing http api to find and update docs in Mongo and I want to know if it was a connection error or the doc I am looking for doesn't exist in DB. In both cases I receive `nothing` in return. Is it possible to "catch" this DEBUG info to interpretate it as an error or maybe to throw such Authentication failures?

**Comment by ivborissov** [comment]
Thanks! Yes, I see, other requests throw "catchable" errors )

**Comment by felipenoris** [comment]
This should now be fixed. If it works all fine to you, I'll tag a new version for the package.

Thanks!

**Comment by ivborissov** [comment]
Yes, now it works the way i have expected it to work. Thanks a lot!
