### ISSUE TITLE
length for Mongoc.Cursor{Mongoc.Collection} ?

### ISSUE THREAD

**Issue by phaverty** [felipenoris/Mongoc.jl#22]
I'm looking for convenient/efficient ways to get queries into a DataFrame. It would be super convenient to have a `length` function on cursors to allow list comprehensions to work. Probably cursors were not meant to be used this way, but still it would be nice. :-)

**Comment by felipenoris** [comment]
Hi!
I believe MongoDB does not provide the size of a cursor. The only I know to go about this is to use `collect(cursor)`, which will return a `Vector{BSON}`, and then use the vector. Would this suit your needs?

**Comment by phaverty** [comment]
That will work, thanks!
