### ISSUE TITLE
Select fields to output with `find`

### ISSUE THREAD

**Issue by ivborissov** [felipenoris/Mongoc.jl#27]
Hi,
What is the right way to get only requested fields with `find/find_one`?
An example of what I am trying to do can be the following `collection`:
```
    Mongoc.BSON("""{ "cust_id" : "A123", "amount" : 500, "status" : "A" }"""),
    Mongoc.BSON("""{ "cust_id" : "A123", "amount" : 250, "status" : "A" }"""),
    Mongoc.BSON("""{ "cust_id" : "B212", "amount" : 200, "status" : "A" }"""),
    Mongoc.BSON("""{ "cust_id" : "A123", "amount" : 300, "status" : "D" }""")
```
I want to `Mongoc.find_one(collection,Mongoc.BSON("""{ "cust_id" : "B212" }"""))` but only `["amount", "status"]` fields.

**Comment by felipenoris** [comment]
Please, check the options field at http://mongoc.org/libmongoc/current/mongoc_collection_find_with_opts.html .

As an example:

```julia
function find_contract_codes(::MongoContractSource, criteria::Dict=Dict()) :: Vector{String}
    result = Vector{String}()

    let
        bson_filter = Mongoc.BSON(criteria)
        bson_options = Mongoc.BSON("""{ "projection" : { "_id" : true }, "sort" : { "_id" : 1 } }""")
        for bson_document in Mongoc.find(get_contracts_collection(), bson_filter, options=bson_options)
            push!(result, bson_document["_id"])
        end
    end

    return result
end
```

This is something dificult to find in libmongo docs, and probably something I should update in the docs for Mongoc.jl.

**Comment by ivborissov** [comment]
Ahh, thanks a lot! Sorry, I forgot about the options field

**Comment by felipenoris** [comment]
Example added to docs by 78029950778875e771a3ae5d392ddf264f8fdc53.
