### ISSUE TITLE
How to get libmongoc built with ENABLE_SSL?

### ISSUE THREAD

**Issue by kindlychung** [felipenoris/Mongoc.jl#32]
Got this error while pinging a db:

```
The SCRAM_SHA_1 authentication mechanism requires libmongoc built with ENABLE_SSL.
in top-level scope at base/none
in ping at Mongoc/N4NkA/src/api.jl:73
in command_simple at Mongoc/N4NkA/src/api.jl:57
in error at base/error.jl:33
```

Any suggestions on how to solve this? Thanks.

**Comment by felipenoris** [comment]
Maybe it is a bug related to #9. Can you share your connection string?

**Comment by kindlychung** [comment]
This one, for example:

```
mongodb://heroku_jnnvww95:e3as6ujmcb304vhudut46dh7p0@ds237955.mlab.com:37955/heroku_jnnvww95
```

**Comment by felipenoris** [comment]
@kindlychung thanks! I'll take a look at this. I'm trying to compile libmongoc with its dependencies in order to solve this kind of issue.

**Comment by felipenoris** [comment]
@kindlychung , #33 should fix this and it is now merged to the master branch.
Can you check if the problem persists?

**Comment by kindlychung** [comment]
Yeah, it works now.  Thanks. 

```
BSON("{ "ok" : 1.0, "operationTime" : { "$timestamp" : { "t" : 1554319695, "i" : 1 } }, "$clusterTime" : { ...
```

**Comment by felipenoris** [comment]
Great! I'll tag a new version in a couple days.
