### ISSUE TITLE
wrap findAndModify()

### ISSUE THREAD

**Issue by phaverty** [felipenoris/Mongoc.jl#45]
It would be awesome to have access to the mongo function `findAndModify`. I've been looking into implementing [this trick](https://www.tutorialspoint.com/mongodb/mongodb_autoincrement_sequence.htm) for an auto-incrementing field. On a related note, would also be great to have documentation on calling a server-side javascript function from Mongoc.jl. I'm not sure it is possible at the moment as the function call ends up as a character string in the BSON object. but, maybe I'm missing something. I've tried running `findAndModify` with the simple command interface, without success. Might we have some more documentation on using that with more complex functions?  Any help in this area would be much appreciated!

**Comment by felipenoris** [comment]
I didn't know it was possible with MongoDB. Awesome! I'll be glad to take a look at that.

**Comment by felipenoris** [comment]
Regarding the `findAndModify`, I can add support to call [this function](http://mongoc.org/libmongoc/current/mongoc_collection_find_and_modify.html).

But on the javascript function subject, I guess there is no way to do that AFAIK.
The trick you mentioned actually defines the javascript in the client side. So it would not be different from implementing it in Julia. I also found that you can [store JavaScript functions on the server](https://docs.mongodb.com/manual/tutorial/store-javascript-function-on-server/), but it looks like that you need to load them in the client side before using it. So I guess you would need the JavaScript interpreter (which is bundled in the mongo shell) do make use of them, but, again, wouldn't be different from implementing the function in Julia.

**Comment by phaverty** [comment]
Oh, I think I overlooked the point about the javascript function actually being in the client. That isn't so useful, I agree. Wrapping `mongoc_collection_find_and_modify()` seems like the way to go, I agree.

**Comment by felipenoris** [comment]
Closed by 126a56f.
