### ISSUE TITLE
NaN output is enclosed as Dict{String, Any} instead of Float value

### ISSUE THREAD

**Issue by shivchawla** [felipenoris/Mongoc.jl#46]
Some NaN output has a different output format than regular Float output. For ex: 

`Any[Dict{String,Any}("\$date"=>"2018-09-24T04:34:00Z"), Dict{String,Any}("\$numberDouble"=>"NaN"), Dict{String,Any}("\$numberDouble"=>"NaN"), Dict{String,Any}("\$numberDouble"=>"NaN"), Dict{String,Any}("\$numberDouble"=>"NaN"), 0], Any[Dict{String,Any}("\$date"=>"2018-09-24T04:35:00Z"), 203.5, 203.5, 203.15, 203.5, 203]
`

Should it not be handled at API level and formatted as Float64 NaN instead of dictionary?

Thanks

**Comment by felipenoris** [comment]
Thanks for reporting this!

Can you provide a code that generates thos result?

**Comment by shivchawla** [comment]
```
query = Dict("securityid" => securityid, 
                "priority"=> priority,
                "date" => DateTime(date), 
            )

 docs = Mongoc.collect(Mongoc.find(datacollection, Mongoc.BSON(query)))
    
    for d in docs

        doc = JSON.parse(Mongoc.as_json(d))

        columndata = doc["data"]["columns"]
        actualdata = doc["data"]["values"]

        #Format the actual data (with new mongoc module, simplae datetime array field comes as dictionary field)
        if actualdata != nothing && length(actualdata) > 0
            actualdata = [
                [DateTime(collect(values(dataRow[1]))[1][1:end-1]); dataRow[2:end]] 
                for dataRow in actualdata]
        end
    end

```
Below is the data format I work with if it helps!

![Screen Shot 2019-04-28 at 1 41 55 AM](https://user-images.githubusercontent.com/1387632/56854606-e44f0a80-6956-11e9-9c69-686afd061eb1.png)
![Screen Shot 2019-04-28 at 1 40 55 AM](https://user-images.githubusercontent.com/1387632/56854607-e4e7a100-6956-11e9-889a-24452f19c7be.png)

Thanks for taking out the time!

**Comment by felipenoris** [comment]
I see. I think this is a side effect of converting the BSON to JSON.

For instance, this code below works as you would expect:

```julia
julia> doc = Mongoc.BSON( "a" => 1, "b" => NaN )
BSON("{ "a" : 1, "b" : { "$numberDouble" : "NaN" } }")

julia> doc["b"]
NaN

julia> typeof(doc["b"])
Float64
```

The `as_json` triggers the C API functions [bson_as_canonical_extended_json](http://mongoc.org/libbson/current/bson_as_canonical_extended_json.html) or [bson_as_relaxed_extended_json](http://mongoc.org/libbson/current/bson_as_relaxed_extended_json.html) which prints the floating point number that way.

I would suggest to operate directly in the BSON document as if it were a regular Julia `Dict`, as in this code:

```julia
query = Dict("securityid" => securityid, 
                "priority"=> priority,
                "date" => DateTime(date), 
            )

 docs = Mongoc.collect(Mongoc.find(datacollection, Mongoc.BSON(query)))
    
    for d in docs

        columndata = d["data"]["columns"]
        actualdata = d["data"]["values"]
...
```

Does this work for you?

**Comment by shivchawla** [comment]
In the beginning, I used BSON directly but there was some weird issue (which I didn't write down). I then converted it to JSON to make it work. But I agree that working directly with BSON makes more sense. I will try it again and see if BSON works fine in my use case. 

Thanks!

**Comment by felipenoris** [comment]
Alright, let me know if you have any trouble dealing with BSON directly.
