### ISSUE TITLE
Connect using SSL

### ISSUE THREAD

**Issue by weera-tech** [felipenoris/Mongoc.jl#56]
Is there any documentation about connecting using SSL?
What I need is equivalent of code below wrote in NodeJS:

`var MongoClient = require('mongodb').MongoClient,
  f = require('util').format,
  fs = require('fs');

// Read the certificate authority
var ca = [fs.readFileSync(__dirname + "/ssl/ca.pem")];
var cert = fs.readFileSync(__dirname + "/ssl/client.pem");
var key = fs.readFileSync(__dirname + "/ssl/client.pem");

// Connect validating the returned certificates from the server
MongoClient.connect("mongodb://localhost:27017/test?ssl=true", {
  server: {
      sslValidate:true
    , sslCA:ca
    , sslKey:key
    , sslCert:cert
    , sslPass:'10gen'
  }
}, function(err, db) {
  db.close();
});`

**Comment by felipenoris** [comment]
This is currently not supported.

**Comment by weera-tech** [comment]
Thank you for the comment
is this not supported in mongoc or julia at all?

**Comment by felipenoris** [comment]
libmongoc supports it, I guess. Support can be added to this Julia package. Just have to be implemented.

**Comment by weera-tech** [comment]
will it take a long or not?

**Comment by felipenoris** [comment]
@weera-tech , looks like the driver supports passing these options in the URI. Please refer to http://mongoc.org/libmongoc/current/mongoc_ssl_opt_t.html#configuration-through-uri-options .

See if this works for you.

**Comment by weera-tech** [comment]
Unfortunately, I am new in Julia and I don't know where should I exactly use it. in the types.jl?

**Comment by felipenoris** [comment]
This is not a Julia thing. You should pass these options in the mongodb url connect string, along with `ssl=true`.

**Comment by weera-tech** [comment]
As I know, mongodb uri cannot include ssl cert path.
https://docs.mongodb.com/manual/tutorial/configure-ssl-clients/
ssl path should be defined in uri option object

**Comment by felipenoris** [comment]
Regardless of what mongo shell supports, the libmongoc library says it supports sslClientCertificateKeyFile, sslClientCertificateKeyPassword, sslCertificateAuthorityFile, sslAllowInvalidCertificates and sslAllowInvalidHostnames in the Connection URI. Have you tried that?

**Comment by weera-tech** [comment]
Could you please provide a step by step guide about where I should exactly put these variables? I have no experience for libmongoc.

**Comment by felipenoris** [comment]
Please refer to https://docs.mongodb.com/manual/reference/connection-string/#connections-connection-options for information on how to set options in the mongo URI.
