### ISSUE TITLE
Parsing dates

### ISSUE THREAD

**Issue by DarioCorno** [felipenoris/Mongoc.jl#64]
I'm not able in any way to query using dates in a MongoDb collection that has a Date field.

Let's say I have a date string (but it also doesn't work with DateTime or Date, ISO dates or mongo ISODate() function'

`dsiso = "2015-02-14"`

I'm trying to create a valid BSON to get the dates greater than my date with:

`mngQry = string("""{ "date" : { "\$gte" : "new Date('$dsiso')" } }""")`

resulting in this bson string:
`{ "date" : { "$gte" : "new Date('2015-02-14')" } }`

that I use with:

`docs = Mongoc.find( mngCollection, Mongoc.BSON(mngQry) )`

I did try to put quotes around ISODate, passing the actual date string without quotes, whatever I try it gives me a BSON parsing error or no results at all.

`for doc in docs`
`   show(doc)`
`end`

The same string in mongo shell gives correct results:

`db.getCollection("mycoll").find({date : { $gte: new Date('2015-02-14')} })`

What's the correct way to query dates using Mongoc and Julia?

**Comment by felipenoris** [comment]
Please, refer to https://felipenoris.github.io/Mongoc.jl/stable/tutorial/#BSON-Documents-1.
