### ISSUE TITLE
Documents don't show up in the database.

### ISSUE THREAD

**Issue by zalmoxis** [felipenoris/Mongoc.jl#73]
I am trying to write with push! append! and find_and_modify but nothing shows up in the db even though julia is returning positive results (including object IDs and insert counts).
I tried to use the "mongo" binary client and using the same client I can confirm the rows are added and persist on server restart.
I also can't seem to read anything back using find.
I tried 2 versions of the mongodb server: 4.4 and 3.2 ... and the version of libmongoc I use is the one that comes with debian:
The following additional packages will be installed:                                                                       
  libbson-dev libsnappy-dev
The following NEW packages will be installed:
  libbson-dev libmongoc-1.0-0 libmongoc-dev libsnappy-dev

I am not sure if Mongoc.jl build it's own libmongoc or if it would try to use the system one?
Is there some journaling transaction commit that's not happening? Am I doing something wrong?

PS. I am on Julia 1.6.0 on Debian 10/buster and have tried to use Mongoc.jl with "add Mongoc" as well as the github url - same result.

**Comment by felipenoris** [comment]
Hi! This library uses `libmongoc` built by https://github.com/JuliaBinaryWrappers/MongoC_jll.jl . So, binaries are pre-built.

As long as you're not explicitly using the [transaction API](https://felipenoris.github.io/Mongoc.jl/stable/transaction/), documents are stored into the database once they´re inserted using the [CRUD API](https://felipenoris.github.io/Mongoc.jl/stable/crud/#Insert-1).

Given that I haven't used this package on Julia v1.6 , I can't tell if there's something fundamentally wrong with this package, although I think that is not the case. I think your best bet is to either run the package tests on your environment, or go through the [Tutorial](https://felipenoris.github.io/Mongoc.jl/stable/tutorial/) and debug the simple case of just reading documents from a collection.

**Comment by zalmoxis** [comment]
Thanks for the info... I at least know it isn't a debian package issue. As you can see here julia claims the objects get created on mongo but Mongoc.jl seems to fail to read any object at all including those inserted from the mongo client. I am actually concerned about this ptr-nothing here: ),Ptr{Nothing} @0x0000000003192f10)
Is that the equivalent of a null pointer or something like that?
https://puu.sh/Hxh9X/0d07017b1f.png
`
julia> client = Mongoc.Client("mongodb://localhost:27017")

Client(URI("mongodb://localhost:27017"))

julia> newcol=client["newdb"]["newcol"]
Collection(Database(Client(URI("mongodb://localhost:27017")), "newdb"), "newcol")

julia> result = push!(newcol, Mongoc.BSON("""{ "hello" : "world" }"""))
Mongoc.InsertOneResult{Mongoc.BSONObjectId}(BSON("{ "insertedCount" : 1 }"), BSONObjectId("60729e72837573009002f7bb"))

julia> result = push!(newcol, Mongoc.BSON("""{ "hello" : "world" }"""))
Mongoc.InsertOneResult{Mongoc.BSONObjectId}(BSON("{ "insertedCount" : 1 }"), BSONObjectId("60729e96837573009002f7bc"))

julia> Mongoc.find(newcol)
Mongoc.Cursor{Mongoc.Collection}(Collection(Database(Client(URI("mongodb://localhost:27017")), "newdb"), "newcol"),Ptr{Nothing} @0x0000000003192f10)
`

**Comment by felipenoris** [comment]
Please, read the docs. Mongoc.find returns a cursor. You have to iterate the cursor to read the documents.

https://felipenoris.github.io/Mongoc.jl/stable/tutorial/#Querying-Documents-1

**Comment by zalmoxis** [comment]
Oups! I couldn't originally find the doc and used the test file as the example. I can query the objects from another julia instance which is great. However, they never show up when using the "mongo" client. I wonder if the db or collection name has some prefix when using Mongoc.jl?

**Comment by felipenoris** [comment]
There's no added prefix when using Mongoc.jl . Database and collection names match the names informed in the string `"newdb"`  or `"newcol"` in your code.

Maybe you can inspect from the mongo shell the available databases and collections using `show dbs` and `show collections` to check what is going wrong. https://docs.mongodb.com/manual/reference/mongo-shell/
