### ISSUE TITLE
Support converting composite types, named tuples...? (possible implementation provided)

### ISSUE THREAD

**Issue by OliverColeman** [felipenoris/Mongoc.jl#74]
For a project I'm working on I need to store and retrieve composite types into/from mongodb. I wrote some code to extend Mongoc to allow this, along with some other common types. Before making a PR I'd like to gauge interest on incorporating such functionality into this package. Thoughts? Example usage of the attached code:

```julia
struct TestTypeA{T}
    val1::Dict{String, T}
end

struct TestTypeB{T, V}
    primitive::Int64
    parametric::T
    array::Array{T}
    tuple::Tuple{Bool, T}
    dict::Dict{String, T}
    namedTuple::NamedTuple{(:c, :d),Tuple{Int64,T}}
    type::DataType
    subtype::TestTypeA{V}
end


t = TestTypeB{Float64, Dict{String, Int64}}(
    1, 
    2.3, 
    [4, 5.0], 
    (true, 6), 
    Dict("a"=>7, "b"=>8),
    (c=9, d=9.1),
    Int8,
    TestTypeA(Dict("ans" => Dict("is" => 42)))
)

bson = Mongoc.BSON(t)
println(bson)

obj = as_type(TestTypeB{Float64, Dict{String, Int64}}, bson)
println(obj)

# Produces:
# BSON("{ "primitive" : 1, "parametric" : 2.2999999999999998224, "array" : [ 4.0, 5.0 ], "tuple" : [ true, 6.0 ], "dict" : { "b" : 8.0, "a" : 7.0 }, "namedTuple" : { "c" : 9, "d" : 9.0999999999999996447 }, "type" : "Int8", "subtype" : { "val1" : { "ans" : { "is" : 42 } } } }")
# TestTypeB{Float64, Dict{String, Int64}}(1, 2.3, [4.0, 5.0], (true, 6.0), Dict("b" => 8.0, "a" => 7.0), (c = 9, d = 9.1), Int8, TestTypeA{Dict{String, Int64}}(Dict("ans" => Dict("is" => 42))))
```
[mongotalk.jl.txt](https://github.com/felipenoris/Mongoc.jl/files/6368301/mongotalk.jl.txt)

**Comment by felipenoris** [comment]
Hi @OliverColeman !
Nice work!
I would leave this kind of feature in a separate package. This package just gives the minimal features to handle BSON e interact with MongoDB. 

See https://github.com/felipenoris/BSONSerializer.jl and https://github.com/JuliaIO/BSON.jl

**Comment by OliverColeman** [comment]
Okay, I thought that would be the most likely case. Thanks for Mongoc, by the by :)
