### ISSUE TITLE
bson(::Dict) should be bson(::AbstractDictionary)

### ISSUE THREAD

**Issue by mgm7734** [felipenoris/Mongoc.jl#96]
I was trying to use an OrderedDict to make it easier to compare a generated queries and noticed this.   All the tests pass with this trivial change. 

Patchfile:
diff --git a/src/bson.jl b/src/bson.jl
index 45a9c74..c7a9a1e 100644
--- a/src/bson.jl
+++ b/src/bson.jl
@@ -378,7 +378,7 @@ function BSON(args::Pair...)
     return result
 end
 
-BSON(dict::Dict) = BSON(dict...)
+BSON(dict::AbstractDict) = BSON(dict...)
 
 """
     as_json(bson::BSON; canonical::Bool=false) :: String

**Comment by felipenoris** [comment]
Nice! Can you submit a PR?

**Comment by mgm7734** [comment]
I tried, but no permission.
```
$ git push --set-upstream origin mgmdev
ERROR: Permission to felipenoris/Mongoc.jl.git denied to mgm7734.
```

**Comment by felipenoris** [comment]
Done in eed1c0a79e410e5009248c49c1c563fe3015d2b0
